### ISSUE TITLE
Please, reopen issue #18 still persist in new version 1.6.3

### ISSUE THREAD

**Issue by esvarc** [J-Dill/NoMoWanderer#21] opened 2024-01-25 13:08 UTC
Sorry for the late response, but the GitHub notification ended up in spam and I found it while cleaning out the spam folder.

However, the instructions on how to reproduce the error are valid, the entire installation is available packaged as a ZIP, just replace v201-nomowanderer-1.20.1-1.6.2.jar with nomowanderer-1.20.1_1.6.3.jar. In my test I did this and downloaded the current version from https://www.curseforge.com/minecraft/mc-mods/nomowanderer.

In my case I'm using Forge version 47.2.20 and MC version 1.20.1

Package and details are in #18 closed ticket whole instance is still available in onedrive (https://1drv.ms/u/s!AsuclbmnGMOphrNnYmqiRs6Egrjb6w?e=YbSPZ7), just need to replace mod with newer version.

**Comment by francWhite** [comment] 2024-01-25 19:40
We're seeing the same issue on our server running the Direwolf20 1.20 1.12.1 pack using nomowanderer-1.20.1_1.6.3.jar with the same stacktrace.

**Comment by J-Dill** [comment] 2024-01-26 02:04
@esvarc Thanks for the report! I see from your stacktrace that the exception is indeed happening in a piece of code that I did not fix, so I will be working on getting a fix going here soon.

I must admit that I did not open your OneDrive link before because it looked a bit suspicious, but I can see that it is a legit link so I will be using that as an example to try and reproduce this issue.

**Comment by J-Dill** [comment] 2024-01-26 03:44
@esvarc @francWhite This should now be fixed in the latest version for MC1.20.1. I am working on porting the fix to all other versions as well, but for Direwolf20 they will have to update to point to the latest version.

Please confirm that it looks good from your side and then you or I can close this.

PS: I really do appreciate the follow up to the issue, it has helped me to better understand modding and work towards a more permanent solution :)

**Comment by esvarc** [comment] 2024-01-26 07:23
I ill test it, sorry for my late answers, but well done J-Dill :)

**Comment by francWhite** [comment] 2024-02-02 02:50
hey @J-Dill, sorry for my late response. Nevertheless I highly appreciate your quick bugfix! Keep up your work, I also looked into modding a long time ago but soon left it due to the lack of creative ideas haha

Anyway I will test your fix in the Direwolf 20 modpack as soon as they publish a new version. There is already an open issue [(#4608](https://github.com/FTBTeam/FTB-Modpack-Issues/issues/4608)) regarding this update, so hopefully it shouldn't take that long. The reporter of said issue already tested with 1.6.4 and it seems to work. I will close this issue when the new modpack version is released and tested by myself, okay?

**Comment by J-Dill** [comment] 2024-02-02 04:46
@francWhite I appreciate you submitting that bug to the Direwolf pack, definitely helps out!

**Comment by J-Dill** [comment] 2024-02-02 04:48
@esvarc Were you able to confirm that the latest version of NoMoWanderer fixes the issue for your server?

PS: not sure what you were building in that custom modpack but that world looked AWESOME 😄

**Comment by esvarc** [comment] 2024-02-04 18:55
Hi, thank you. No I will not make modpack, but I did it for my friends and we really enjoy playing this tweaked world full of places to explore. I will test it tomorrow and give you feedback. 

I have easy test, I will just do pregen of 5000 x 5000 blocks and if there is still lockup we will see.

**Comment by esvarc** [comment] 2024-02-05 10:30
In short it is fixed,

I did a new test with the updated nomowanderer-1.20.1-1.6.4.jar, I also updated the ctov-3.4.2.jar because someone reported a problem with the newer version of ChoiceTheorem's Overhauled Village.

The test of generating 5000 x 5000 blocks, which is almost 313 x 313 chunks, was 100% successful.

I am also attaching a list of mods that were in the test. The real magic that makes the world interesting are datapacks

```
bettervillages-bountiful-1.19.4.zip
ctov-villager-plus-add-on-v2-0.zip
dungeons-and-taverns-v3.1.0.zip
lost-libraries-1.1.1.zip
morestructures-spacingtweaks-1.20.1-2.1.56.zip
reds-more-structure-v1.0.8-common-spawn-rate.zip
repurposed-structures-better-desert-temples-v8.zip
repurposed-structures-better-dungeons-v5.zip
repurposed-structures-better-jungle-temples-v5.zip
repurposed-structures-better-monuments-v6.zip
repurposed-structures-better-nether-fortress-v6.zip
repurposed-structures-better-witch-huts-v4.zip
repurposed-structures-bountiful-v3.zip
repurposed-structures-bygone-nether-v1.zip
repurposed-structures-villagersplus-v3.zip
villagersplus-supplementaries-compatability.zip
wda-noflyingstructures-owend-1.18.2-1.20.1.zip
```

And then some fixes and modifications via datapacks, such as bug fixes for mods.

[✔️] v201-1.20.1-forge47.1.0-mod-pickupwidelysmp-v1.2.4.jar
  [✔️] v201-adlods-1.20.1-8.1.0.0-build.0142.jar
  [✔️] v201-advanced-xray-forge-1.20.1-2.18.1-build.22.jar
  [✔️] v201-ai-improvements-1.20-0.5.2.jar
  [✔️] v201-apotheosis-1.20.1-7.0.5.jar
  [✔️] v201-apothicattributes-1.20.1-1.1.4.jar
  [✔️] v201-appleskin-forge-mc1.20.1-2.5.1.jar
  [✔️] v201-appliedenergistics2-forge-15.0.15.jar
  [✔️] v201-architectury-9.1.12-forge.jar
  [✔️] v201-attributefix-forge-1.20.1-21.0.4.jar
  [✔️] v201-awesomedungeonend-forge-1.20.1-3.1.1.jar
  [✔️] v201-awesomedungeon-forge-1.20.1-3.2.0.jar
  [✔️] v201-awesomedungeonnether-forge-1.20.1-3.1.1.jar
  [✔️] v201-awesomedungeonocean-forge-1.20.1-3.3.0.jar
  [✔️] v201-backpacked-forge-1.20.1-2.2.5.jar
  [✔️] v201-balm-forge-1.20.1-7.2.1.jar
  [✔️] v201-betteradvancements-1.20.1-0.3.2.161.jar
  [✔️] v201-betterf3-7.0.2-forge-1.20.1.jar
  [✔️] v201-bettervillage-forge-1.20.1-3.2.0.jar
  [✔️] v201-biomesoplenty-1.20.1-18.0.0.598.jar
  [✔️] v201-block-swap-forge-1.20.1-5.0.0.0.jar
  [✔️] v201-bookshelf-forge-1.20.1-20.1.8.jar
  [✔️] v201-bountiful-6.0.3-1.20.1-forge.jar
  [✔️] v201-bygonenether-1.3.2-1.20.x.jar
  [✔️] v201-cagedmobs-1.20.1-forge-2.0.5.jar
  [✔️] v201-canary-mc1.20.1-0.2.7.jar
  [✔️] v201-carryon-forge-1.20.1-2.1.2.7.jar
  [✔️] v201-castle-dungeons-4.0.0-1.20-forge.jar
  [✔️] v201-catalogue-forge-1.20.1-1.8.0.jar
  [✔️] v201-cfm-forge-1.20.1-7.0.0-pre36.jar
  [✔️] v201-chisels-and-bits-forge-1.4.145.jar
  [✔️] v201-chunkloaders-1.2.8a-forge-mc1.20.1.jar
  [✔️] v201-chunksending-1.20.1-2.8.jar
  [✔️] v201-chunky-1.3.92.jar
  [✔️] v201-clienttweaks-forge-1.20-11.1.0.jar
  [✔️] v201-cloth-config-11.1.106-forge.jar
  [✔️] v201-clumps-forge-1.20.1-12.0.0.3.jar
  [✔️] v201-collective-1.20.1-7.30.jar
  [✔️] v201-colossalchests-1.20.1-1.8.4.jar
  [✔️] v201-controllable-forge-1.20.1-0.20.3.jar
  [✔️] v201-controlling-forge-1.20.1-12.0.2.jar
  [✔️] v201-crafttweaker-forge-1.20.1-14.0.32.jar
  [✔️] v201-create-1.20.1-0.5.1.f.jar
  [✔️] v201-creategoggles-1.20.1-0.5.5.e-hf-forge.jar
  [✔️] v201-cristellib-1.1.5-forge.jar
  [✔️] v201-ctov-3.4.2.jar
  [✔️] v201-cupboard-1.20.1-2.1.jar
  [✔️] v201-curios-forge-5.4.6-1.20.1.jar
  [✔️] v201-cyclic-1.20.1-1.12.4.jar
  [✔️] v201-cyclopscore-1.20.1-1.19.0.jar
  [✔️] v201-darkutilities-forge-1.20.1-17.0.3.jar
  [✔️] v201-deepercaves-1.20.1-1.2.3.jar
  [✔️] v201-deuf-1.20.1-1.3.jar
  [✔️] v201-dreadsteel-1.20.1-1.1.6.2.jar
  [✔️] v201-dungeon-crawl-1.20.1-2.3.14.jar
  [✔️] v201-dungeonsarise-1.20.1-2.1.57-release.jar
  [✔️] v201-easy-piglins-1.20.1-1.0.1.jar
  [✔️] v201-easy-villagers-1.20.1-1.0.17.jar
  [✔️] v201-elevatorid-1.20.1-1.8.15.jar
  [✔️] v201-embeddium-0.3.0-mc1.20.1.jar
  [✔️] v201-enchantinginfuser-v8.0.2-1.20.1-forge.jar
  [✔️] v201-enchantsmith-forge-1.0.3-1.20.jar
  [✔️] v201-enderite-cj-forge-mc1.20.1-1.4.2.jar
  [✔️] v201-everycomp-1.20-2.6.18.jar
  [✔️] v201-explorations-forge-1.20.1-1.5.2.jar
  [✔️] v201-explorify-v1.3.0-mc1.20u1.20.1.jar
  [✔️] v201-extraarmor-1.20.1-1.17.4.jar
  [✔️] v201-fastfurnace-1.20.1-8.0.1.jar
  [✔️] v201-fastload-reforged-mc1.20.1-3.4.0.jar
  [✔️] v201-fastsuite-1.20.1-5.0.1.jar
  [✔️] v201-fastworkbench-1.20.1-8.0.2.jar
  [✔️] v201-ferritecore-6.0.1-forge.jar
  [✔️] v201-flatbedrock-forge-3.0.1-build.18-mc1.20.1.jar
  [✔️] v201-flib-1.20.1-0.0.11.jar
  [✔️] v201-forgeconfigscreens-v8.0.2-1.20.1-forge.jar
  [✔️] v201-forgeendertech-1.20.1-11.1.0.1-build.0289.jar
  [✔️] v201-formations-1.0.2-forge-mc1.20.jar
  [✔️] v201-formationsnether-1.0.2.jar
  [✔️] v201-formationsoverworld-1.0.1.jar
  [✔️] v201-framedcompactdrawers-1.20-6.0.0.jar
  [✔️] v201-framework-forge-1.20.1-0.6.16.jar
  [✔️] v201-fullbrightnesstoggle-1.20.1-4.0.jar
  [✔️] v201-gamemenumodoption-mc1.20.1-2.2.1.jar
  [✔️] v201-geophilic-v2.1.0-mc1.20u1.20.2.jar
  [✔️] v201-gildednetherite-cj-forge-mc1.20-1.0.2.jar
  [✔️] v201-global-packs-forge-1.19.4-1.16.2-forge.jar
  [✔️] v201-goblintraders-forge-1.20.1-1.9.3.jar
  [✔️] v201-guardvillagers-1.20.1-1.6.3.jar
  [✔️] v201-hopobettermineshaft-1.20-1.20.1-1.1.8.jar
  [✔️] v201-hopobetterruinedportals-1.20-1.20.2-1.3.7.jar
  [✔️] v201-hopobetterunderwaterruins-1.20-1.20.2-1.1.4b.jar
  [✔️] v201-immediatelyfast-forge-1.2.8-1.20.4.jar
  [✔️] v201-imst-2.1.0.jar
  [✔️] v201-incendium-1.20.4-v5.3.4.jar
  [✔️] v201-inventoryprofilesnext-forge-1.20-1.10.9.jar
  [✔️] v201-invhud.forge.1.20.1-3.4.18.jar
  [✔️] v201-ironchest-1.20.1-14.4.4.jar
  [✔️] v201-ironshulkerbox-1.20.1-5.3.2.jar
  [✔️] v201-itemcollectors-1.1.8-forge-mc1.20.jar
  [✔️] v201-jade-1.20.1-forge-11.6.4.jar
  [✔️] v201-jadeaddons-1.20.1-forge-5.2.2.jar
  [✔️] v201-jearchaeology-1.20.1-1.0.3.jar
  [✔️] v201-jeed-1.20-2.1.6.jar
  [✔️] v201-jeitweaker-forge-1.20.1-8.0.6.jar
  [✔️] v201-jess-1.20.1-forge-1.1.0.jar
  [✔️] v201-journeymap-1.20.1-5.9.18-forge.jar
  [✔️] v201-justenoughadvancements-1.20.1-5.0.1.jar
  [✔️] v201-justenoughbeacons-forge-1.19-1.1.1.jar
  [✔️] v201-justenoughmekanismmultiblocks-1.20.1-4.2.jar
  [✔️] v201-justenoughresources-1.20.1-1.4.0.238.jar
  [✔️] v201-kambrik-6.1.1-1.20.1-forge.jar
  [✔️] v201-kotlinforforge-4.9.0-all.jar
  [✔️] v201-leavesbegone-v8.0.0-1.20.1-forge.jar
  [✔️] v201-libipn-forge-1.20-4.0.1.jar
  [✔️] v201-libraryferret-forge-1.20.1-4.0.0.jar
  [✔️] v201-libx-1.20.1-5.0.12.jar
  [✔️] v201-light-overlay-8.0.0-forge.jar
  [✔️] v201-lootbeams-1.20.1-1.2.3.jar
  [✔️] v201-mcjtylib-1.20-8.0.3.jar
  [✔️] v201-mcw-bridges-2.1.1-mc1.20.1forge.jar
  [✔️] v201-mcw-doors-1.1.0forge-mc1.20.1.jar
  [✔️] v201-mcw-fences-1.1.1-mc1.20.1forge.jar
  [✔️] v201-mcw-furniture-3.2.2-mc1.20.1forge.jar
  [✔️] v201-mcw-lights-1.0.6-mc1.20.1forge.jar
  [✔️] v201-mcw-roofs-2.3.0-mc1.20.1forge.jar
  [✔️] v201-mcw-trapdoors-1.1.2-mc1.20.1forge.jar
  [✔️] v201-mcw-windows-2.2.1-mc1.20.1forge.jar
  [✔️] v201-mekanism-1.20.1-10.4.5.19.jar
  [✔️] v201-mekanismadditions-1.20.1-10.4.5.19.jar
  [✔️] v201-mekanismgenerators-1.20.1-10.4.5.19.jar
  [✔️] v201-mekanismtools-1.20.1-10.4.5.19.jar
  [✔️] v201-memoryleakfix-forge-1.17-1.1.2.jar
  [✔️] v201-modelfix-1.14.jar
  [✔️] v201-modernfix-forge-5.11.1-mc1.20.1.jar
  [✔️] v201-modernui-forge-1.20.1-3.9.0.4-universal.jar
  [✔️] v201-moonlight-1.20-2.8.67-forge.jar
  [✔️] v201-morejeiinfo-forge-1.20.1-1.0.1.jar
  [✔️] v201-mousetweaks-forge-mc1.20-2.25.jar
  [✔️] v201-mvs-4.1.1-1.20-forge.jar
  [✔️] v201-myserveriscompatible-1.20-1.0.jar
  [✔️] v201-neat-1.20-35-forge.jar
  [✔️] v201-netheritehorsearmor-cj-forge-mc1.20-1.4.0.jar
  [✔️] v201-netherportalfix-forge-1.20-13.0.1.jar
  [✔️] v201-netherportalspread-1.20.1-7.8.jar
  [✔️] v201-nofog-1.3.4-1.20.1-forge.jar
  [✔️] v201-nomowanderer-1.20.1-1.6.4.jar
  [✔️] v201-nonconflictkeys-forge-1.19.x-1.20-1.0.0.jar
  [✔️] v201-no-telemetry-1.8.0.jar
  [✔️] v201-notenoughwands-1.20-6.0.1.jar
  [✔️] v201-oculus-mc1.20.1-1.6.13.jar
  [✔️] v201-overflowingbars-v8.0.0-1.20.1-forge.jar
  [✔️] v201-patchouli-1.20.1-81-forge.jar
  [✔️] v201-philips-ruins1.20.1-2.8.jar
  [✔️] v201-placebo-1.20.1-8.3.7.jar
  [✔️] v201-polymorph-forge-0.49.2-1.20.1.jar
  [✔️] v201-puzzleslib-v8.1.16-1.20.1-forge.jar
  [✔️] v201-reiplugincompatibilities-forge-12.0.93.jar
  [✔️] v201-repurposed-structures-7.1.11-1.20.1-forge.jar
  [✔️] v201-resourcepackoverrides-v8.0.2-1.20.1-forge.jar
  [✔️] v201-restrictions-1.20-6.0.1.jar
  [✔️] v201-rex-s-additionalstructures-1.20.x-v.4.2.1.jar
  [✔️] v201-rftoolsbase-1.20-5.0.2.jar
  [✔️] v201-rftoolsbuilder-1.20-6.0.1.jar
  [✔️] v201-rftoolscontrol-1.20-7.0.1.jar
  [✔️] v201-rftoolsdim-1.20-11.0.5.jar
  [✔️] v201-rftoolspower-1.20-6.0.1.jar
  [✔️] v201-rftoolsstorage-1.20-5.0.1.jar
  [✔️] v201-rftoolsutility-1.20-6.0.3.jar
  [✔️] v201-roughlyenoughitems-12.0.684-forge.jar
  [✔️] v201-roughlyenoughprofessions-forge-1.20.1-2.0.2.jar
  [✔️] v201-rubidium-extra-0.5.4-mc1.20.1-build.116.jar
  [✔️] v201-searchables-forge-1.20.1-1.0.2.jar
  [✔️] v201-servertabinfo-1.20-1.3.8.jar
  [✔️] v201-shadowizardlib-1.20.1-1.0.7.jar
  [✔️] v201-shrines-1.20.1-6.0.2.jar
  [✔️] v201-signtastic-1.20-3.0.0.jar
  [✔️] v201-simple-fps-1.20.x-1.3.0.jar
  [✔️] v201-simplestoragenetwork-1.20.1-1.10.0.jar
  [✔️] v201-simplyhouses-1.1.4-1.20.1-forge.jar
  [✔️] v201-smoothboot-mc1.20.1-0.0.3.jar
  [✔️] v201-smoothchunk-1.20.1-3.5.jar
  [✔️] v201-spark-1.10.53-forge.jar
  [✔️] v201-storagedrawers-1.20.1-12.0.2.jar
  [✔️] v201-structory-1.20.2-v1.3.4.jar
  [✔️] v201-structureessentials-1.20.1-3.2.jar
  [✔️] v201-subterrestrial-forge-1.20-2.2.0.jar
  [✔️] v201-supermartijn642configlib-1.1.8-forge-mc1.20.jar
  [✔️] v201-supermartijn642corelib-1.1.16-forge-mc1.20.1.jar
  [✔️] v201-supplementaries-1.20-2.6.12.jar
  [✔️] v201-tagtooltips-1.20.1-1.0.jar
  [✔️] v201-terrablender-forge-1.20.1-3.0.0.169.jar
  [✔️] v201-timecontrol-1.20.1-1.4.0.jar
  [✔️] v201-tony-s-structures-v3.jar
  [✔️] v201-towns-and-towers-1.12-fabric-forge.jar
  [✔️] v201-trimeffects-1.0.3-forge.jar
  [✔️] v201-undergroundvillages-forge-1.20.1-2.1.0.jar
  [✔️] v201-universalenchants-v8.0.0-1.20.1-forge.jar
  [✔️] v201-villagersplus-3.0-forge-for-1.20.1.jar
  [✔️] v201-waystones-forge-1.20-14.1.3.jar
  [✔️] v201-xnet-1.20-6.0.2.jar
  [✔️] v201-yeetusexperimentus-forge-2.3.1-build.6-mc1.20.1.jar
  [✔️] v201-yungsapi-1.20-forge-4.0.2.jar
  [✔️] v201-yungsbetterdeserttemples-1.20-forge-3.0.3.jar
  [✔️] v201-yungsbetterdungeons-1.20-forge-4.0.3.jar
  [✔️] v201-yungsbetterendisland-1.20-forge-2.0.4.jar
  [✔️] v201-yungsbetterjungletemples-1.20-forge-2.0.4.jar
  [✔️] v201-yungsbettermineshafts-1.20-forge-4.0.4.jar
  [✔️] v201-yungsbetternetherfortresses-1.20-forge-2.0.5.jar
  [✔️] v201-yungsbetteroceanmonuments-1.20-forge-3.0.4.jar
  [✔️] v201-yungsbetterstrongholds-1.20-forge-4.0.3.jar
  [✔️] v201-yungsbetterwitchhuts-1.20-forge-3.0.3.jar
  [✔️] v201-yungsbridges-1.20-forge-4.0.3.jar
  [✔️] v201-yungsextras-1.20-forge-4.0.3.jar

**Comment by J-Dill** [comment] 2024-02-06 04:46
Great to hear. Thanks for testing again. Closing this issue then.

**Closed as completed by J-Dill** 2024-02-06 04:46 UTC
